### ISSUE TITLE
Warning: Invalid argument

### ISSUE THREAD

**Issue by g3design** [deviodigital/leafly-specials-wordpress-plugin#1]
Hello,

Love the plugin and how easy it is to use - however... we're having an issue all of a sudden:
Warning: Invalid argument supplied for foreach() in /home/content/45/11497045/html/wp-content/plugins/leafly-specials-wordpress-plugin-master/includes/shortcodes.php on line 133

That is on our front page of http://swellfarmacy.com/

Any help is appreciated!

George

**Comment by robertdevore** [comment]
I'm glad you like the plugin George! Sorry, but Leafly closed it's API down in Feb, so currently this plugin isn't functional.

If they reopen the API, I'll update this plugin, but until that happens, I'm working on [WP Dispensary](www.wpdispensary.com).

**Comment by g3design** [comment]
Weird - it was working a couple weeks back (the last time i checked)..

Thanks for the info.

George

**Comment by robertdevore** [comment]
No problem!
